name: ci-fullstack-workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # This cron expression triggers the job every Sunday at midnight
  

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install
        working-directory: backend


      - name: Run tests
        run: npm test
        working-directory: backend

      # Run the linter.
      - name: run linter
        run: npm run lint
        working-directory: backend

     # Send a console message at completion.
      - name: Completion Message
        run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."

        
